stages:
  - test
  - deploy

Test:
  image: python:3.9
  stage: test
  script:
    - pip3 install poetry
    - pip3 install nox==2020.5.24
    - nox

Deploy:
  stage: deploy
  script:
    - ./publish_package.sh
